sudo: required
dist: xenial

language: cpp

notifications:
  email:
      - jkmtravisnotify@gmail.com

compiler: gcc

branches:
  only:
    - develop
    - master
    - llvm-6

before_install:
  # print the distro information
  - lsb_release -a

  # cache refresh required to install packages
  - sudo apt-get update -qq

  # install dependencies
  - sudo apt-get -y install cmake swig python-dev python-numpy llvm-6.0-dev

  # install roadrunner dependencies via apt:
  - mkdir ~/debs
  - cd ~/debs
  - wget http://cdn.rawgit.com/sys-bio/roadrunner-debs/4d0f7b7/libroadrunner-deps_2.0.7_amd64.deb
  - wget http://cdn.rawgit.com/sys-bio/roadrunner-debs/4d0f7b7/libroadrunner-deps-dev_2.0.7_amd64.deb
  - sudo dpkg -i libroadrunner-deps_2.0.7_amd64.deb
  - sudo dpkg -i libroadrunner-deps-dev_2.0.7_amd64.deb

  - mkdir ~/install

  - echo "TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR"
  # build roadrunner:
  - mkdir -p ~/build/roadrunner

install:
  - cd ~/build/roadrunner
  - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=~/install/roadrunner -DTHIRD_PARTY_INSTALL_FOLDER=/usr -DBUILD_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython2.7.so python2.7 -DBUILD_TESTS=ON -DBUILD_TEST_TOOLS=ON -DUSE_TR1_CXX_NS=OFF -DBUILD_JAVA_INTERFACE=OFF "$TRAVIS_BUILD_DIR"
  - make -j2
  - make install

before_script: true

script:
  - cd ~/build/roadrunner
  - make -j2 && make install
  - ctest -VV
  # display results of compiled tests
  - cat autotest/compiled-test-suite/results.xml
